# Generated by Django 4.2.5 on 2023-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='open_to_work',
            field=models.BooleanField(default=False),
        ),
    ]
