# Generated by Django 4.2.5 on 2023-09-11 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationexperience",
            name="person",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="person",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="person",
        ),
    ]
