# Generated by Django 4.2.5 on 2023-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_educationexperience_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
