# Generated by Django 4.2.5 on 2023-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_person_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="send_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
