name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SSH into DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }} 
        username: ${{ secrets.DROPLET_USERNAME }} 
        password: ${{ secrets.PASSWORD }} 
        script: |
            cd /var/www/PortfolioWebsite/
            ls
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            supervisorctl restart portfolio
