name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Burada ana dalınızın adını kullanın

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: SSH into DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }} 
        username: ${{ secrets.DROPLET_USERNAME }} 
        password: ${{ secrets.PASSWORD }} 

    - name: Deploy Django Project
      run: |
        ls 
        cd /var/www/PortfolioWebsite/
        git pull origin main
    
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt
    
    - name: Migrate Database
      run: |
        python manage.py migrate
    
    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Update Server
      run: |
        supervisorctl restart portfolio

