name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: SSH into DigitalOcean Droplet
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
        ssh-known-hosts: ${{ secrets.DROPLET_KNOWN_HOSTS }}
        ssh-strict: true
        ssh-args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
        ssh-port: 22
        remote-user: ${{ secrets.DROPLET_USERNAME }}
        remote-host: ${{ secrets.DROPLET_IP }}
        working-directory: /var/www/PortfolioWebsite/

    - name: Deploy Django Project
      run: |
        ls
        git pull origin main

    - name: Activate Virtual Environment
      run: |
        source .venv/bin/activate

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Migrate Database
      run: |
        python manage.py migrate

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Update Server
      run: |
        supervisorctl restart portfolio
